#!/bin/bash

if [ ! $# -eq 0 ]; then
    docker container run --rm -it -v  "$(PWD)":/current-workspace -w "/current-workspace" chent11/cross-compiler:cortex_m4-nano_newlib-hf "$@"
else
    echo "Error: need a parameter"
fi
