#!/bin/sh

DOCKER_IMAGE=chent11/cross-compiler:cortex_m4-nano_newlib-hf
docker_cmd() {
    docker container run --rm -v "$(PWD)":/$(PWD) -w "/$(PWD)" $DOCKER_IMAGE "$@"
}

docker_cmd arm-none-eabi-objdump $@
